### ISSUE TITLE
When multiple IIC sensors are present, only one is shown on the display

### ISSUE THREAD

**Issue by AkosLukacs** [Seeed-Studio/SenseCraft-Wio#16]
**Describe the bug**
Connected SHT40 and SGP30 sensors using a Y groove cable to the right side groove port. But only the temp/hum sensor's data is shown on the screen. If I disconnect the temperature sensor, the CO2 & VOC data is displayed. 
Using the E5 LoRa groove module in the left port data is sent to the dashboard, and the dashboard does show data from both sensors, so it seems to be a display bug

**To Reproduce**
1. Install v.0.2 release
2. Connect two IIC sensors like the SHT40 and SGP30 with either an Y groove splitter or the groove IIC hub
3. Scroll to the right on the "SENSE" screen
4. Only one sensor is shown on the screen

**Expected behavior**
If more than one IIC sensor is connected, all sensor's data should be shown

**Comment by ghost** [comment]
yes, correct. the v0.2 version only can display one external grove sensor. it detects the sensor type by the I2C address.  we will look into that.

**Comment by Maxwelltoo** [comment]
this issue has been resolved in v0.4, now you can connect up to three IIC sensors and they can be displayed on the screen at the same time.
