### ISSUE TITLE
To-Do lists

### ISSUE THREAD

**Issue by Dangerousfish** [Seeed-Studio/SenseCraft-Wio#18]
The current v1.1 code contains a number of references to "to-do" items. Copying links to these from the code so that updates can be tracked.

***To-Do links***

**English Translations**

**ui.cpp**

- [StatusMachine](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L245)
- [NetworkStatus](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L433)
- [DataFilter](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L824)
- [NetworkStatus](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L829)
- [DataFilter](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L899)
- [NetworkStatus](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L904)
- [EmptyDataUnit](https://github.com/Dangerousfish/SenseCraft/blob/v1.1/src/ui.cpp#L245)

**Original Comments**

**ui.cpp**

- [StatusMachine](https://github.com/Seeed-Studio/SenseCraft/blob/v1.1/src/ui.cpp#L245)
- [NetworkStatus](https://github.com/Seeed-Studio//SenseCraft/blob/v1.1/src/ui.cpp#L433)
- [DataFilter](https://github.com/Seeed-Studio//SenseCraft/blob/v1.1/src/ui.cpp#L824)
- [NetworkStatus](https://github.com/Seeed-Studio//SenseCraft/blob/v1.1/src/ui.cpp#L829)
- [DataFilter](https://github.com/Seeed-Studio//SenseCraft/blob/v1.1/src/ui.cpp#L899)
- [NetworkStatus](https://github.com/Seeed-Studio//SenseCraft/blob/v1.1/src/ui.cpp#L904)
- [EmptyDataUnit](https://github.com/Seeed-Studio//SenseCraft/blob/v1.1/src/ui.cpp#L245)

**Comment by baorepo** [comment]
The software has been released and no such problems exist
