### ISSUE TITLE
WiFi not working in v0.3

### ISSUE THREAD

**Issue by dkvaughan1** [Seeed-Studio/SenseCraft-Wio#22]
**Describe the bug**
On the wio display, under Uplink, with WiFi selected, it is stuck at "Waiting for configuration..."

**To Reproduce**
1. Go to 'Uplink'
2. Click on 'WiFi'
3. See error

**Expected behavior**
The wio terminal should connect to wifi. My wio terminal connects when I use v0.2, but does not connect with v0.3

**Comment by Chunchun-tian** [comment]
You can open the device's serial port at a baud rate of 9600, and then check the serial port log that

**Comment by Chunchun-tian** [comment]
One more thing, in v0.3 the wifi connection platform has changed from Ubidots to Microsoft Azure IoT Central, you need to refer to the documentation to connect to the latest platform

https://wiki.seeedstudio.com/Connect-Wio-Terminal-to-Azure-IoT-Central/

**Comment by Dangerousfish** [comment]
I cannot replicate this issue on v0.3.

Wifi works fine, issue should be raised on Discord for further guidance but @Chunchun-tian 's last reply is the correct one and this issue should be closed.

**Comment by dkvaughan1** [comment]
I was following some online documentation that said I just needed to put my wifi name and password into the config.txt file. This worked with v0.2, but not v0.3. Thank you for the clarification that I need azure credentials in order for my local wifi to connect to the wio.

**Comment by Dangerousfish** [comment]
@ me on the seeed Discord if I can help get you any further @dkvaughan1

- Fish
