### ISSUE TITLE
VL53L0X sensor could display with v0.4.uf2 but not the build by the latest code

### ISSUE THREAD

**Issue by hayschan** [Seeed-Studio/SenseCraft-Wio#26]
**Describe the bug**
When I flash v0.4.uf2 from [releases](https://github.com/Seeed-Studio/SenseCraft/releases/download/v0.4/SenseCraft-v0.4.uf2), VL53L0X could be detected and read as expected when I plug into Wio Terminal right port.

But when I `git clone` the [repo](https://github.com/Seeed-Studio/SenseCraft), and build it myself. It fails to build because the missing lib of VL53L0X. 

Then I add `seeed-studio/Grove Ranging sensor - VL53L0X@^1.1.1` in `platform.ini`. After that, I could build and upload successfully. 

However, when I plug in the Grove Ranging sensor - VL53L0X hardware using the right port, it could not recognize the sensor.

**Comment by hayschan** [comment]
Even if I build with the source code provided alongside v0.4.uf2 from releases, the problem persist.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/25737801/200267002-bc96c6c5-c18a-47b2-8135-0588ad4ee51e.png">

**Comment by Maxwelltoo** [comment]
My bad, I forgot to update the list of dependent libraries. 
You are doing the right thing, but the main branch of the library is based on a hardware i2c implementation, for Wio Terminal hardware, software i2c should be used. The correct dependency is `https://github.com/Seeed-Studio/Grove-Ranging-sensor-VL53L0X#K1101`, and subsequent commits have added this item.
