### ISSUE TITLE
Graphical Display and SD-Card are not working

### ISSUE THREAD

**Issue by matthiasbirkich** [Seeed-Studio/SenseCraft-Wio#29]
**Describe the bug**
I really appreciate that great development of a non-code sensing platform :-). Thank you very much for your work!
Are you so kind enough to tell me, what I am doing wrong and how I can solve that issue?
1) According to https://wiki.seeedstudio.com/K1100-quickstart/ 
With the WIO-Terminal D51R (WiFi BL5 Firmware 2.1.3 or 2.0.1) some modes of SenseCraft (SenseCraft-v0.2-20220907.uf2) are not working on any WIO-Terminal I tested.
2) The Examples from TinyML are not working, when I press the middle of the 5way bottom.
3) The graphical display is not working, when I press the middle of the 5way bottom.
4) The FS-Card (SD-card) is not working, when I press the middle of the 5way bottom.
6) The Firmware is not displayed when I start WIO-Terminal (Only "SenseCAP 1100" is shown)
!The mid bottom is working propper for e.g. WiFi connection!
7) According to https://github.com/Seeed-Studio/SenseCraft-Wio?tab=readme-ov-file
When I do the firmware update with Visual Studio code, nothing works.

When I would dream for the future of this very helpful concept and device:
1) Make it possible to choose IN865 frequency
2) Go for Arduino-Cloud for the MQTT service
3) Many WiFi-connections need SSID, USER and PASSWORD. Implementation of this would be great.
4) The Implementation of the Particle sensor 3301 (https://wiki.seeedstudio.com/Grove-Laser_PM2.5_Sensor-HM3301/) would turn the WIO-SenseCraft to an scientific and Citizen Science Tool, which everybody wants to have (schools, universities, government, households,...).
Thanks a lot!!!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [edge]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dangerousfish** [comment]
Hey @matthiasbirkich

Youve done a great job explaining the features you need, but it's not abundantly clear what steps you've taken to produce the error.

What issues did you face when flashing the latest firmware specifically?

**Comment by matthiasbirkich** [comment]
Dear fish,

what I found out today:
in the wiki there is a wrong link to an repository of AI vision, NOT
SenseCraft.
Also the UF2 is not the newest one in the wiki of seeedstudio.

Best regards
Matthias


Fish ***@***.***> schrieb am Do. 15. Feb. 2024 um 09:35:

**Comment by Dangerousfish** [comment]
So what requires fixing?

If it's just a broken link on the wiki, you can contact Seeed Studio via their support channel instead of this Git?

You have highlighted a number of things you wish to improve, but it's very difficult to assist with resolving or tracing issues with the descriptions you have provided so far.

**Comment by matthiasbirkich** [comment]
Dear fish,

thank you very much for the quick support and the great work you do! I‘ll
go to contact Seeed Studio for the broken link.

Best regards
Matthias


Fish ***@***.***> schrieb am Fr. 16. Feb. 2024 um 06:01:
