### ISSUE TITLE
WiFi connection fails

### ISSUE THREAD

**Issue by matthiasbirkich** [Seeed-Studio/SenseCraft-Wio#30]
**Describe the bug**
Dear Dangerousfish,

today I installed successive all available Firmware and tested the performance on my WIO-Terminal D51R.
Everything with one exception is working very well (Thanx a lot for this).
Unfortunately only ver0.2 is able to connect to the WiFi. Version K1101-v0.4 have not enough memory to edit the config.txt.
That is the reason, why it is also not working to connect to Azure/Ubidots.
Are you so kind to tell me, why version 3-4.1 are not doing there job and if you are able to reproduce this erratic behavior?

**To Reproduce**

**Expected behavior**
Connection to my private WiFi-network
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matthiasbirkich** [comment]
Dear Dangerousfish,

I am still learning! Now I have total success with the K1011 v0.4 Firmware to send data to the Ubidots Cloud.
Sorry for buzzer you! All the best for you! Greatings, Matthias

**Comment by Dangerousfish** [comment]
Well done @matthiasbirkich 👌😊
