### ISSUE TITLE
How to access uf2 download?

### ISSUE THREAD

**Issue by usermctech** [Seeed-Studio/SenseCraft-Wio#31]
How to access uf2 download?

**Comment by baorepo** [comment]
I'm sorry, I don't know exactly what you're talking about, but you can describe more about your situation, your needs, your problems. @usermctech

**Comment by usermctech** [comment]
You said to download the senscraft wio uf2, but I can't find a link to it.

Wysłano z programu Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by baorepo** [comment]
@usermctech  This issue is discussed under the software repository.  Please refer to the readme documentation for specific usage.

**Comment by usermctech** [comment]
I click "Download from here" but it gives me only the source code

**Comment by baorepo** [comment]
@usermctech   uf2 file is here
![图片](https://github.com/user-attachments/assets/8659ba3a-9dfc-49f1-a9fb-6c48103bce84)

**Comment by usermctech** [comment]
https://github.com/Seeed-Studio/ModelAssistant/releases



The link to download (this is not it)?

Wysłano z programu Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by baorepo** [comment]
@usermctech  May I answer your question? Is there anything else I can do for you?

**Comment by usermctech** [comment]
Still can't find the download link (please send a link to download site)

Wysłano z programu Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by baorepo** [comment]
https://github.com/Seeed-Studio/SenseCraft-Wio/releases/download/v0.4.1/SenseCraft-k1100-v0.4.uf2 @usermctech  Here you go.

**Comment by usermctech** [comment]
Thanks!

Wysłano z programu Outlook dla systemu Android<https://aka.ms/AAb9ysg>
________________________________
